<?php

namespace Journal\JournalBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorArticleRepository extends ArticleRepository
{
    public function getLatestArticles($iLimit = null)
    {
    	$this->discriminator = 'author';
    	return parent::getLatestArticles($iLimit);
    }
}
