<?php

namespace Journal\JournalBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Journal\JournalBundle\Entity\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getLatestTags($iLimit = null)
    {
		$oQB = $this->createQueryBuilder('t')
		            ->select('t')
 		            ->addOrderBy('t.created', 'DESC');

		if (false === is_null($iLimit))
			$oQB->setMaxResults($iLimit);
		
		return $oQB->getQuery()
		           ->getResult();
    }
    
    
    public function getOrAddTagByName($sTagName) {
        if (!($oTag = $this->findOneBy(['name' => $sTagName]))) {
        	$oTag = new Tag();
        	$oTag->setName($sTagName);
        	$this->_em->persist($oTag);
        	$this->_em->flush();
        	
        }
        
        return $oTag;    	
    }
}
